-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versione server:              10.4.32-MariaDB - mariadb.org binary distribution
-- S.O. server:                  Win64
-- HeidiSQL Versione:            12.6.0.6765
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dump della struttura del database fiabe
CREATE DATABASE IF NOT EXISTS `fiabe` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */;
USE `fiabe`;

-- Dump della struttura di tabella fiabe.countries
CREATE TABLE IF NOT EXISTS `countries` (
  `ISO` char(2) NOT NULL,
  `NAME` char(100) NOT NULL,
  PRIMARY KEY (`ISO`),
  UNIQUE KEY `NAME` (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dump dei dati della tabella fiabe.countries: ~230 rows (circa)
INSERT INTO `countries` (`ISO`, `NAME`) VALUES
	('AF', 'Afghanistan'),
	('AL', 'Albania'),
	('DZ', 'Algeria'),
	('AS', 'American Samoa'),
	('AD', 'Andorra'),
	('AO', 'Angola'),
	('AI', 'Anguilla'),
	('AQ', 'Antarctica'),
	('AG', 'Antigua and Barbuda'),
	('AR', 'Argentina'),
	('AM', 'Armenia'),
	('AW', 'Aruba'),
	('AU', 'Australia'),
	('AT', 'Austria'),
	('AZ', 'Azerbaijan'),
	('BS', 'Bahamas'),
	('BH', 'Bahrain'),
	('BD', 'Bangladesh'),
	('BB', 'Barbados'),
	('BY', 'Belarus'),
	('BE', 'Belgium'),
	('BZ', 'Belize'),
	('BJ', 'Benin'),
	('BM', 'Bermuda'),
	('BT', 'Bhutan'),
	('BA', 'Bosnia and Herzegovina'),
	('BW', 'Botswana'),
	('BV', 'Bouvet Island'),
	('BR', 'Brazil'),
	('IO', 'British Indian Ocean Territory'),
	('BN', 'Brunei Darussalam'),
	('BG', 'Bulgaria'),
	('BF', 'Burkina Faso'),
	('BI', 'Burundi'),
	('KH', 'Cambodia'),
	('CM', 'Cameroon'),
	('CA', 'Canada'),
	('CV', 'Cape Verde'),
	('KY', 'Cayman Islands'),
	('CF', 'Central African Republic'),
	('TD', 'Chad'),
	('CL', 'Chile'),
	('CN', 'China'),
	('CX', 'Christmas Island'),
	('CC', 'Cocos (Keeling) Islands'),
	('CO', 'Colombia'),
	('KM', 'Comoros'),
	('CG', 'Congo'),
	('CK', 'Cook Islands'),
	('CR', 'Costa Rica'),
	('HR', 'Croatia'),
	('CU', 'Cuba'),
	('CY', 'Cyprus'),
	('CZ', 'Czech Republic'),
	('DK', 'Denmark'),
	('DJ', 'Djibouti'),
	('DM', 'Dominica'),
	('DO', 'Dominican Republic'),
	('EC', 'Ecuador'),
	('EG', 'Egypt'),
	('SV', 'El Salvador'),
	('GQ', 'Equatorial Guinea'),
	('ER', 'Eritrea'),
	('EE', 'Estonia'),
	('ET', 'Ethiopia'),
	('FK', 'Falkland Islands (Malvinas)'),
	('FO', 'Faroe Islands'),
	('FJ', 'Fiji'),
	('FI', 'Finland'),
	('FR', 'France'),
	('GF', 'French Guiana'),
	('PF', 'French Polynesia'),
	('TF', 'French Southern Territories'),
	('GA', 'Gabon'),
	('GM', 'Gambia'),
	('GE', 'Georgia'),
	('DE', 'Germany'),
	('GH', 'Ghana'),
	('GI', 'Gibraltar'),
	('GR', 'Greece'),
	('GL', 'Greenland'),
	('GD', 'Grenada'),
	('GP', 'Guadeloupe'),
	('GU', 'Guam'),
	('GT', 'Guatemala'),
	('GG', 'Guernsey'),
	('GN', 'Guinea'),
	('GW', 'Guinea-Bissau'),
	('GY', 'Guyana'),
	('HT', 'Haiti'),
	('HM', 'Heard Island and McDonald Islands'),
	('VA', 'Holy See (Vatican City State)'),
	('HN', 'Honduras'),
	('HK', 'Hong Kong'),
	('HU', 'Hungary'),
	('IS', 'Iceland'),
	('IN', 'India'),
	('ID', 'Indonesia'),
	('IR', 'Iran'),
	('IQ', 'Iraq'),
	('IE', 'Ireland'),
	('IM', 'Isle of Man'),
	('IL', 'Israel'),
	('IT', 'Italy'),
	('JM', 'Jamaica'),
	('JP', 'Japan'),
	('JE', 'Jersey'),
	('JO', 'Jordan'),
	('KZ', 'Kazakhstan'),
	('KE', 'Kenya'),
	('KI', 'Kiribati'),
	('KW', 'Kuwait'),
	('KG', 'Kyrgyzstan'),
	('LA', 'Lao Peoples Democratic Republic'),
	('LV', 'Latvia'),
	('LB', 'Lebanon'),
	('LS', 'Lesotho'),
	('LR', 'Liberia'),
	('LY', 'Libya'),
	('LI', 'Liechtenstein'),
	('LT', 'Lithuania'),
	('LU', 'Luxembourg'),
	('MO', 'Macao'),
	('MG', 'Madagascar'),
	('MW', 'Malawi'),
	('MY', 'Malaysia'),
	('MV', 'Maldives'),
	('ML', 'Mali'),
	('MT', 'Malta'),
	('MH', 'Marshall Islands'),
	('MQ', 'Martinique'),
	('MR', 'Mauritania'),
	('MU', 'Mauritius'),
	('YT', 'Mayotte'),
	('MX', 'Mexico'),
	('MC', 'Monaco'),
	('MN', 'Mongolia'),
	('ME', 'Montenegro'),
	('MS', 'Montserrat'),
	('MA', 'Morocco'),
	('MZ', 'Mozambique'),
	('MM', 'Myanmar'),
	('NA', 'Namibia'),
	('NR', 'Nauru'),
	('NP', 'Nepal'),
	('NL', 'Netherlands'),
	('NC', 'New Caledonia'),
	('NZ', 'New Zealand'),
	('NI', 'Nicaragua'),
	('NE', 'Niger'),
	('NG', 'Nigeria'),
	('NU', 'Niue'),
	('NF', 'Norfolk Island'),
	('MP', 'Northern Mariana Islands'),
	('NO', 'Norway'),
	('OM', 'Oman'),
	('PK', 'Pakistan'),
	('PW', 'Palau'),
	('PA', 'Panama'),
	('PG', 'Papua New Guinea'),
	('PY', 'Paraguay'),
	('PE', 'Peru'),
	('PH', 'Philippines'),
	('PN', 'Pitcairn'),
	('PL', 'Poland'),
	('PT', 'Portugal'),
	('PR', 'Puerto Rico'),
	('QA', 'Qatar'),
	('RO', 'Romania'),
	('RU', 'Russian Federation'),
	('RW', 'Rwanda'),
	('KN', 'Saint Kitts and Nevis'),
	('LC', 'Saint Lucia'),
	('MF', 'Saint Martin (French part)'),
	('PM', 'Saint Pierre and Miquelon'),
	('VC', 'Saint Vincent and the Grenadines'),
	('WS', 'Samoa'),
	('SM', 'San Marino'),
	('ST', 'Sao Tome and Principe'),
	('SA', 'Saudi Arabia'),
	('SN', 'Senegal'),
	('RS', 'Serbia'),
	('SC', 'Seychelles'),
	('SL', 'Sierra Leone'),
	('SG', 'Singapore'),
	('SX', 'Sint Maarten (Dutch part)'),
	('SK', 'Slovakia'),
	('SI', 'Slovenia'),
	('SB', 'Solomon Islands'),
	('SO', 'Somalia'),
	('ZA', 'South Africa'),
	('GS', 'South Georgia and the South Sandwich Islands'),
	('SS', 'South Sudan'),
	('ES', 'Spain'),
	('LK', 'Sri Lanka'),
	('PS', 'State of Palestine'),
	('SD', 'Sudan'),
	('SR', 'Suriname'),
	('SJ', 'Svalbard and Jan Mayen'),
	('SZ', 'Swaziland'),
	('SE', 'Sweden'),
	('CH', 'Switzerland'),
	('SY', 'Syrian Arab Republic'),
	('TJ', 'Tajikistan'),
	('TH', 'Thailand'),
	('TL', 'Timor-Leste'),
	('TG', 'Togo'),
	('TK', 'Tokelau'),
	('TO', 'Tonga'),
	('TT', 'Trinidad and Tobago'),
	('TN', 'Tunisia'),
	('TR', 'Turkey'),
	('TM', 'Turkmenistan'),
	('TC', 'Turks and Caicos Islands'),
	('TV', 'Tuvalu'),
	('UG', 'Uganda'),
	('UA', 'Ukraine'),
	('AE', 'United Arab Emirates'),
	('GB', 'United Kingdom'),
	('US', 'United States'),
	('UM', 'United States Minor Outlying Islands'),
	('UY', 'Uruguay'),
	('UZ', 'Uzbekistan'),
	('VU', 'Vanuatu'),
	('VN', 'Viet Nam'),
	('WF', 'Wallis and Futuna'),
	('EH', 'Western Sahara'),
	('YE', 'Yemen'),
	('ZM', 'Zambia'),
	('ZW', 'Zimbabwe');

-- Dump della struttura di tabella fiabe.fiabe
CREATE TABLE IF NOT EXISTS `fiabe` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `titolo` varchar(255) NOT NULL,
  `descrizione` varchar(255) NOT NULL,
  `autore` varchar(255) NOT NULL,
  `fiaba` longtext NOT NULL,
  `paese` char(2) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `paese` (`paese`),
  CONSTRAINT `fiabe_ibfk_1` FOREIGN KEY (`paese`) REFERENCES `countries` (`ISO`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dump dei dati della tabella fiabe.fiabe: ~0 rows (circa)
INSERT INTO `fiabe` (`id`, `titolo`, `descrizione`, `autore`, `fiaba`, `paese`) VALUES
	(1, 'Cenerentola', 'Una giovane ragazza trattata male dalla sua matrigna e dalle sue sorellastre, ma che alla fine trova la felicità grazie a una scarpetta di cristallo.', 'Charles Perrault', 'C\'era una volta una giovane ragazza di nome Cenerentola, che viveva con la sua crudele matrigna e le sue due sorellastre egoiste. Cenerentola era costretta a fare tutti i lavori domestici, mentre le sue sorellastre vivevano nella ricchezza e nel lusso. Un giorno, il re del regno decise di organizzare un grande ballo per trovare una moglie per suo figlio, il principe. Tutte le fanciulle del regno furono invitate, ma la matrigna di Cenerentola le proibì di partecipare. Con il cuore spezzato, Cenerentola pianse nel cortile. Improvvisamente, una fata madrina apparve e, con un tocco della sua bacchetta magica, trasformò una zucca in una carrozza, i topolini in cavalli e il vestito logoro di Cenerentola in un magnifico abito da ballo. Cenerentola andò al ballo e il principe si innamorò perdutamente di lei. Ma alla mezzanotte, Cenerentola dovette fuggire, lasciando dietro di sé una scarpetta di cristallo. Il principe cercò ovunque la misteriosa ragazza che si adattava alla scarpetta, finché non la trovò. E così, Cenerentola sposò il principe e vissero felici e contenti per sempre.', 'FR'),
	(2, 'Biancaneve', 'Una principessa che fugge nella foresta per sfuggire alla malvagità della sua matrigna, solo per essere accolta da sette nani.', 'Brothers Grimm', 'In una lontana terra, c\'era una bella principessa di nome Biancaneve, la cui bellezza faceva invidia alla sua malvagia matrigna. La matrigna, gelosa della bellezza di Biancaneve, cercò di ucciderla, ma Biancaneve fuggì nella foresta e si rifugiò in una piccola casetta abitata da sette nani. I nani accettarono Biancaneve e la protessero dalla matrigna malvagia. Tuttavia, la matrigna, travestita da vecchia venditrice, riuscì a far mangiare a Biancaneve una mela avvelenata che la fece cadere in un sonno profondo. Il principe del regno, passando di lì, la vide addormentata e se ne innamorò. Baciò Biancaneve, rompendo l\'incantesimo e risvegliandola. Biancaneve e il principe si sposarono e vissero felici per sempre, mentre la matrigna malvagia ricevette la sua giusta punizione.', 'DE'),
	(3, 'La Bella Addormentata nel Bosco', 'Una principessa che viene maledetta a dormire per cent\'anni da una strega malvagia, solo per essere risvegliata da un bacio d\'amore.', 'Charles Perrault', 'In un castello lontano, c\'era una principessa di nome Aurora, conosciuta da tutti come la Bella Addormentata. La sua nascita era stata celebrata con grande gioia da tutto il regno, ma una malvagia strega era stata trascurata nell\'invito al battesimo e, infuriata, lanciò una terribile maledizione su Aurora. Prima del suo sedicesimo compleanno, la principessa si sarebbe punta il dito su un fuso e sarebbe caduta in un sonno profondo che avrebbe durato cento anni. Il re, disperato per salvare sua figlia, ordinò che tutti i fusi del regno fossero distrutti. Ma la maledizione si avverò comunque. Aurora cadde in un sonno profondo, insieme a tutto il castello. Cento anni dopo, un giovane principe esplorò il castello addormentato e trovò Aurora. Affascinato dalla sua bellezza, le diede un bacio d\'amore che la risvegliò dal suo lungo sonno. Il principe e Aurora si innamorarono e, alla fine, si sposarono, portando la felicità nel regno e spezzando per sempre l\'incantesimo della Bella Addormentata.', 'FR'),
	(4, 'La Sirenetta', 'Una giovane sirena che sogna di diventare umana per amore di un principe.', 'Hans Christian Andersen', 'Nel profondo del mare viveva una giovane sirena di nome Ariel, che sognava di vivere sulla terra. Un giorno, Ariel salvò un principe umano da un naufragio e se ne innamorò perdutamente. Desiderosa di diventare umana, Ariel chiese aiuto alla strega del mare, che le diede una pozione magica. Tuttavia, diventare umana significava perdere la sua voce melodiosa. Ariel accettò il sacrificio e divenne umana, ma il principe non la riconobbe senza la sua voce. Alla fine, Ariel sacrificò la sua vita per salvare il principe da un\'altra tragedia. Tuttavia, il suo sacrificio non fu invano, poiché il suo spirito divenne un essere celeste e trovò la pace nell\'oltretomba.', 'DK'),
	(5, 'Aladino e la Lampada Magica', 'Un giovane ragazzo che scopre una lampada magica e usa i suoi desideri per migliorare la sua vita e sconfiggere il male.', 'Antoine Galland', 'In una città lontana, c\'era un giovane ragazzo di nome Aladino, che viveva con sua madre in povertà. Un giorno, Aladino trovò una lampada magica in una caverna e, strofinandola, fece apparire un genio che gli concedette tre desideri. Con l\'aiuto del genio, Aladino divenne ricco e potente. Tuttavia, un malvagio stregone cercò di rubare la lampada magica per i suoi scopi malvagi. Con astuzia e coraggio, Aladino sconfisse lo stregone e riportò la lampada magica al suo posto. Alla fine, Aladino capì che il vero tesoro non era la ricchezza, ma l\'amore e l\'amicizia.', 'CN'),
	(6, 'Pinocchio', 'Un burattino di legno che desidera diventare un vero ragazzo e impara importanti lezioni di vita lungo il percorso.', 'Carlo Collodi', 'Geppetto era un vecchio falegname che desiderava ardentemente avere un figlio. Un giorno, scolpì un burattino di legno e lo chiamò Pinocchio. Ma la sua creazione prende vita grazie alla magia di una fata buona e comincia a comportarsi come un vero ragazzo, anche se è incline a bugie e cattive azioni. Pinocchio intraprende un\'avventura per diventare umano, ma affronta molte difficoltà e tentazioni lungo il percorso. Alla fine, impara importanti lezioni di vita sulla sincerità, l\'onestà e l\'amore per gli altri, e diventa finalmente un vero ragazzo.', 'IT'),
	(7, 'Hansel e Gretel', 'Due fratelli che vengono abbandonati nel bosco e trovano una casa di marzapane abitata da una strega malvagia.', 'Brothers Grimm', 'Hansel e Gretel erano due fratelli che vivevano in una capanna con il loro padre e la loro crudele matrigna. Un giorno, la matrigna decise di abbandonare i bambini nel bosco perché non c\'era cibo sufficiente per tutti. Hansel e Gretel si persero nel bosco e trovarono una casa fatta di marzapane e dolci. Ma la casa era abitata da una strega malvagia che li catturò e li mise in una gabbia. Hansel e Gretel riuscirono a ingannare la strega e a liberarsi. Tornati a casa, trovarono il padre pentito e insieme vissero felici per sempre.', 'DE'),
	(8, 'Raperonzolo', 'Una giovane ragazza con lunghi capelli che viene rinchiusa in una torre da una strega malvagia.', 'Brothers Grimm', 'In una lontana terra, c\'era una giovane ragazza di nome Raperonzolo, che era famosa per i suoi lunghi capelli dorati. Un giorno, una strega malvagia la rinchiuse in una torre senza porte né scale. Raperonzolo visse lì per anni, finché un giorno un principe la sentì cantare e la trovò. Il principe chiese a Raperonzolo di lasciare cadere i suoi capelli, così poté arrampicarsi sulla torre e salvarla. Raperonzolo e il principe fuggirono insieme e vissero felici per sempre.', 'DE'),
	(9, 'Il Libro della Giungla', 'Le avventure di Mowgli, un bambino allevato da lupi nella giungla indiana.', 'Rudyard Kipling', 'Mowgli era un bambino abbandonato che fu trovato e cresciuto da una famiglia di lupi nella giungla indiana. Con l\'aiuto del suo mentore, il saggio orso Baloo, e del rigido pantera nera Bagheera, Mowgli imparò le leggi della giungla e combatté contro il malvagio tigre di Bengala, Shere Khan. Lungo il percorso, Mowgli incontrò altri animali della giungla, come il serpente Kaa e il re delle scimmie, Re Louie. Alla fine, Mowgli scelse di lasciare la giungla per vivere tra gli esseri umani, ma il suo cuore rimase sempre con i suoi amici animali.', 'GB'),
	(10, 'Il Principe Felice', 'La storia di una statua di un principe e un rondine che sacrificano tutto per aiutare i bisognosi.', 'Oscar Wilde', 'In una città lontana c\'era una grande statua di un principe ricoperta d\'oro, che aveva sempre vissuto nell\'abbondanza e nel lusso. Un giorno, una rondine si posò ai suoi piedi e vide le lacrime dei poveri e dei bisognosi. Il principe chiese alla rondine di portare i suoi occhi d\'oro ai poveri, e la rondine acconsentì. Successivamente, il principe chiese alla rondine di portare il suo rivestimento d\'oro al giovane scrittore povero, e la rondine acconsentì di nuovo. Alla fine, la rondine sacrificò la propria vita per aiutare una famiglia bisognosa e il cuore del principe si spezzò. Ma la sua buona azione portò la felicità a molte persone e, alla fine, il principe e la rondine furono ricompensati con la vita eterna nel giardino del Paradiso.', 'GB');

-- Dump della struttura di tabella fiabe.utenti
CREATE TABLE IF NOT EXISTS `utenti` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `mail` varchar(255) NOT NULL,
  `username` varchar(255) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dump dei dati della tabella fiabe.utenti: ~0 rows (circa)
INSERT INTO `utenti` (`id`, `mail`, `username`, `password_hash`) VALUES
	(1, 'a@a', 'a', '$2b$04$MMezp9ZCtDK7oIgobLT1ruI7GiPliej9S.5ds7kkrW/vfMF/cE/iy');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
